services:
  django:
    image: backend:0.2
    build:
      context: ./config/django-image
    volumes:
      - ./src/django/:/usr/src/app:delegated
    environment:
      DATABASE_PASS: ${DATABASE_PASS}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_HOST: ${DATABASE_HOST}
      DJANGO_SU_NAME: ${DJANGO_SU_NAME}
      DJANGO_SU_PASSWORD: ${DJANGO_SU_PASSWORD}
      DJANGO_SU_EMAIL: ${DJANGO_SU_EMAIL}
    ports:
      - 8000:8000
  postgres:
    image: postgres:16.3
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_NAME}
    command: postgres -c 'max_connections=600'
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data:delegated
      - ./conf/postgres/:/docker-entrypoint-initdb.d/


