# Generated by Django 5.0.6 on 2024-07-09 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApiNoteUser', '0002_note_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='descripcion',
            field=models.TextField(max_length=25000),
        ),
    ]
